name: BuildPR
on:
    pull_request:
        branches:
            - main
jobs:
    buildTest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version-file: ".nvmrc"
            - uses: pnpm/action-setup@v2
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 9
                  run_install: false
            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
            - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
              name: Setup pnpm cache
              with:
                  path: |
                      ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                      ${{ github.workspace }}/apps/frontend/.next/cache
                  key: ${{ runner.os }}-pnpm-store-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-nextjs
            - name: Install dependencies
              run: pnpm install --frozen-lockfile -r
            - run: pnpm run lint
            - run: pnpm run test
            - run: pnpm run build
